# Generated by Django 5.1.1 on 2024-09-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
